### ISSUE TITLE
Pagination fails due to start cursor encoded as query parameter

### ISSUE THREAD

**Issue by ashdavies** [BoD/klibnotion#24]
The Notion [documentation](https://developers.notion.com/reference/post-database-query) shows that `START_CURSOR` is encoded in the request body, but here it's added as a URL parameter, which as of the API version `2021-08-16` responds with a validation error.

`https://api.notion.com/v1/databases/{DATABASE_ID}/query?start_cursor={PAGE_ID}`

```
{
  "object": "error",
  "status": 400,
  "code": "validation_error",
  "message": "query failed validation: query.start_cursor should be not present, instead was `\"e8635964-722c-4aed-a33d-ac3709280c99\"`."
}
```

This behaviour can be reproduced by setting up the request in manually (cUrl/Postman/Insomnia), and then changing this to a JSON body request.

It looks as though the `START_CURSOR` should be removed from `NotionService.kt`, and encoded with a `@SerialName` annotation in the `ApiDatabaseQuery` data class. There may also be other request body classes that need updating as well.

**Comment by BoD** [comment]
Good catch! And thanks a lot for the PR!

I'm not sure how I never noticed this, and if it worked at some point or actually never worked at all and I just never noticed. It's not that easy to test pagination cases since you need a lot of data (and for now the only "tests" I have are the samples).

**Comment by ashdavies** [comment]
Yeah, I figured it was an edge case, it's also possible that they changed it for a few requests. The `start_cursor` is still a query parameter for the block APIs. It may be possible to set up a test case just with the last returned item, expecting an empty return set. I'll try and take a look at that if I get some time.

Thanks for the library, by the way, it's proving quite useful for my side projects 👍
