### ISSUE TITLE
Possibility to archive pages

### ISSUE THREAD

**Issue by MaaxGr** [BoD/klibnotion#3]
AFAIK there is no possibility to delete/archive a page with your api.

The notion dev documentation points out that an update-request should be performed
- https://developers.notion.com/reference/archive-delete-a-page
- https://developers.notion.com/reference/patch-page

Possibilities how this could be implemented in my opinion:
- create archivePage()/unarchivePage() method in NotionClientImpl
- add a archived boolean to the updatePage() method

Could you look into it?

**Comment by MaaxGr** [comment]
Here is a quick and dirty solution, how it can be implemented: https://github.com/MaaxGr/klibnotion/compare/4c8d4afa5b0e893d322f709005d2218452d1fa8c...cf4ab478c134d6f6013cbeb0c8b2f51ef560ff9c

**Comment by BoD** [comment]
Hello, World!  Thanks for the issue and the contribution!  I've incorporated your commit, and changed the API a bit (one method with boolean instead of 2 methods). It's in the `release/1.6.0` branch, which will be the base for the next release of the library.
