### ISSUE TITLE
Timezone Problem

### ISSUE THREAD

**Issue by MaaxGr** [BoD/klibnotion#4]
# Application Side

I try to update a date-property of a notion database with this line of code:
```
propertyList.date("todoist_update_time", DateOrDateRange(DateTime(Timestamp(System.currentTimeMillis())), null))
```

The date is updated, but unfortunatelly in the wrong timezone (2 hours to early. My Timezone is GMT+02)

# Library Side

In the TimestampFormatter-Class the Timezone is forced to be GMT.

```
private val simpleDateFormat = SimpleDateFormat(format).apply {
    // Set the default timezone to GMT for the case where it's not present in the date to parse
    // which is the case when it's a date without a time.
    timeZone = TimeZone.getTimeZone("GMT")
}
```
The DateTime-Constructor consumes a Timestamp, which is not bound to a timezone, so i can't control the timezone from outside.

My proposal would be to use two different SimpleDateFormat-objects. One for parsing and one for formatting.
```
    private val formatFormatter = SimpleDateFormat(format)

    private val parseFormatter = SimpleDateFormat(format).apply {
        // Set the default timezone to GMT for the case where it's not present in the date to parse
        // which is the case when it's a date without a time.
        timeZone = TimeZone.getTimeZone("GMT")
    }

    actual fun parse(formattedDate: String): Timestamp {
        return parseFormatter.parse(formattedDate)
    }

    actual fun format(timestampToFormat: Timestamp): String {
        return formatFormatter.format(timestampToFormat)
    }
```

**Comment by BoD** [comment]
Fixed in 1.6.0.  You can now pass a time zone id (will use the system's by default).
