### ISSUE TITLE
NullPointerException on ApiPropertyValueFormulaConverter.apiToModel

### ISSUE THREAD

**Issue by mothinx** [BoD/klibnotion#5]
Hi BoD and first of all thank you for your work.

I can query a simple database like a charm using:
```
List<Page> pages =
				client.getDatabases().queryDatabase(NOTION_DATABASE_ID, null,null, new Pagination()).get().results;
```
![image](https://user-images.githubusercontent.com/9392139/132828970-a08a779b-3436-4ed8-bba8-8d8b9b7b82d2.png)

but when i try working with my database with fancy attributes, i got a NullPointerException on ApiPropertyValueFormulaConverter.apiToModel

here is the attributes of my database:
![image](https://user-images.githubusercontent.com/9392139/132829216-9b027502-baa0-49d2-a8a2-9e31bf331d16.png)

When i try to debug, it's seems to throw null pointer exception when trying to convert **Next Do Date** formula column.
Here is the attributes in cause i think:
```
5 = {SelectPropertySpecImpl@3300} "SelectPropertySpecImpl(name=Récurrence?, id=ZIie, options=[SelectOptionImpl(name=Quotidien, id=71b3542e-6374-4ec3-80ad-f3f4e6c89a27, color=GRAY), SelectOptionImpl(name=Hebdomadaire, id=766db0a8-6e2c-4d25-a950-58601bb5726f, color=BLUE), SelectOptionImpl(name=Mensuel, id=cdddcdd4-8252-4f65-902b-9047625024d8, color=RED), SelectOptionImpl(name=Trimestriel, id=7bbeeca8-c0e6-4b7c-abda-c3acb783a91e, color=BROWN), SelectOptionImpl(name=6 Mois, id=ce73c619-ee0d-4f51-a1a4-afc3e63ef8e9, color=YELLOW), SelectOptionImpl(name=Annuel, id=46db212d-fa98-4e53-929a-1e4a0883e28c, color=GREEN)])"
9 = FormulaPropertySpecImpl(name=Recurrence en jours, id=zudh, expression=if(prop("Récurrence?") == "6 Mois", 180, if(prop("Récurrence?") == "Quotidien", 1, if(prop("Récurrence?") == "Hebdomadaire", 7, if(prop("Récurrence?") == "Mensuel", 30, if(prop("Récurrence?") == "Trimestriel", 90, if(prop("Récurrence?") == "Annuel", 365, 0)))))))
11 = {FormulaPropertySpecImpl@3306} "FormulaPropertySpecImpl(name=Next Do Date, id={vAO, expression=dateAdd(prop("Do Date"), prop("Recurrence en jours"), "days"))"
12 = {DatePropertySpecImpl@3307} "DatePropertySpecImpl(name=Do Date, id=~CiJ)"


```
Récurrence?  column can be null, maybe it's that.

Exception:

> java.util.concurrent.ExecutionException: java.lang.NullPointerException
> 	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
> 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
> 	at NotionGoogleTaskSynchronizer.main(NotionGoogleTaskSynchronizer.java:64)
> Caused by: java.lang.NullPointerException
> 	at org.jraf.klibnotion.internal.api.model.property.value.formula.ApiPropertyValueFormulaConverter.apiToModel(ApiPropertyValueFormulaConverter.kt:64)
> 	at org.jraf.klibnotion.internal.api.model.property.value.ApiPropertyValueConverter.apiToModel(ApiPropertyValueConverter.kt:90)
> 	at org.jraf.klibnotion.internal.api.model.property.value.ApiPropertyValueConverter.apiToModel(ApiPropertyValueConverter.kt:59)
> 	at org.jraf.klibnotion.internal.api.model.ApiConverter.apiToModel(ApiConverter.kt:31)
> 	at org.jraf.klibnotion.internal.api.model.page.ApiPageConverter.apiToModel(ApiPageConverter.kt:39)
> 	at org.jraf.klibnotion.internal.api.model.page.ApiPageConverter.apiToModel(ApiPageConverter.kt:35)
> 	at org.jraf.klibnotion.internal.api.model.ApiConverter.apiToModel(ApiConverter.kt:31)

**Comment by BoD** [comment]
Hi! Thanks for the report. I am currently not in front of a PC but I will have to have a look ASAP!

**Comment by mothinx** [comment]
Let me know if you need more sample data.

**Comment by BoD** [comment]
All right, I had a chance to have a look and indeed this happens when a formula of type date is empty (formula returns nothing).  This is actually already fixed on `master` ([here](https://github.com/BoD/klibnotion/commit/4d3123ca28084a2b2a51aec682ce189aae6cea30)) but hasn't been published yet!  I will try to publish a new version soon, which will contain the fix.

**Comment by BoD** [comment]
@mothinx I have just published [v1.7.0](https://github.com/BoD/klibnotion/releases/tag/v1.7.0) which should resolve the issue. Please telle me if that works :)

**Comment by mothinx** [comment]
@BoD  Thank you! I will try the new version this evening and keep you in touch.

**Comment by mothinx** [comment]
can't find new version on maven central : https://mvnrepository.com/artifact/org.jraf/klibnotion

**Comment by BoD** [comment]
Woops! Sorry about that, I'm not sure what happened.  I published again, you should see it now - tell me if that works.

**Comment by mothinx** [comment]
Work like a charm.
Now i need to find something fun to do with Notion. Thank you for your work.

**Comment by BoD** [comment]
Thanks! I'm glad it worked.
